### ISSUE TITLE
How to add additional conditions to .When()?

### ISSUE THREAD

**Issue by efie45** [richardszalay/mockhttp#107]
I tried searching for this answer via Stackoverflow and Google but all the posts are littered with other generic ways to mock http requests and I would like to stick to this library if it's possible. This question is two-fold:

1. Is there a way to mock requests when any string is passed into the url? i.e.
```csharp
var fakeHttp = new MockHttpMessageHandler();
fakeHttp
  .When(It.IsAny<string>())
  .Respond("text/plain", "some content")
```

2. More generally is there a way to add other boolean type conditions to `.When()`? For example, if you want to return one thing for the first three times the http client is called and something else for the others? For testing a polly policy for example.

**Comment by richardszalay** [comment]
> 1. Is there a way to mock requests when any string is passed into the url? i.e.

Yes, `When("*")` should work.

> 2. More generally is there a way to add other boolean type conditions to .When()? For example, if you want to return one thing for the first three times the http client is called and something else for the others? For testing a polly policy for example.

Yes, but I'll continue below as it doesn't account for the scenario you're describing. If you want to have a different response in an ordered sequence, use `Expect` instead of when. Check out the readme with a rundown of how Expect works vs When.

```csharp
fakeHttp.Expect("*").Response(HttpStatusCode.Conflict);
fakeHttp.Expect("*").Response(HttpStatusCode.Conflict);
fakeHttp.Expect("*").Response(HttpStatusCode.OK);
```

The more general (non-order related) answer to your question is that you can pass in a `Func` to `With` and then even put that behind an extension methods on `MockedRequest`:

```csharp
public static SomeMockedRequestExtensions
{
  public static MockedRequest WithCompanyHeader(this MockedRequest request)
    => request.WithHeader("X-Company", "My Company");

  public static MockedRequest WithHttpVersion(this MockedRequest request, Version versionToMatch)
    => request.With(r => r.Version == versionToMatch);
}
```
