### ISSUE TITLE
Case Insensitive URLs

### ISSUE THREAD

**Issue by camiller2** [richardszalay/mockhttp#11]
Steps to Reproduce:
1) Call mockHttpMessageHandler.Expect(url).Respond(**object**) with a url that contains capital letters and where object is of type **T**.
2) Continue a test that calls a method which uses an HttpClient with the supplied mockHttpMessageHandler.  This method internally creates a Uri object from the same url string (with capital letters).  This in essence makes all letters lowercase.

Expected result: http call returns successful response and response.Content.ReadAsAsync<**T**>() returns "**object**".

Actual result: http call returns successful response, but response.Content.ReadAsAsync<**T**>() returns "**object**" throws an exception: 

> "System.ArgumentNullException

>  : Value cannot be null.
Parameter name: content"

Workaround: make "**url**" all lowercase.

**Comment by richardszalay** [comment]
[As per the W3](https://www.w3.org/TR/WD-html40-970708/htmlweb.html):

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive

The version of MockHttp released today (1.2.2) now uses a Uri on both ends of a Url comparison when the Uri is absolute, so that may fix your problem. Otherwise, I would say it is working as designed.

If you need the URL to be lowercase, that should be part of your application logic.

**Comment by richardszalay** [comment]
Alternatively, you could also create your own project-specific CaseInsensitiveUrlMatcher with a WithUrl extension method overload that takes a boolean flag for case sensitivity.
