### ISSUE TITLE
Not seeing anyway to follow redirects

### ISSUE THREAD

**Issue by f3z0** [richardszalay/mockhttp#115]
We have some logic that I would like to test, we expect the http client to follow a redirect, as I am not seeing anyway to follow the redirect we are unable to test that part of our code. It would be nice to configure a response to redirect with something like:

```
var list = new List<KeyValuePair<string, string>>();
            list.Add(new KeyValuePair<string, string>("Location", "https://example.com/test"));
            mockHttp.When(HttpMethod.Post, "*/test")
                    .Respond(HttpStatusCode.PermanentRedirect, list, new StringContent(""));
```

and then be able to request that HttpClient have AllowFollowRedirect enabled when we get the ToHttpClient. This would allow us to mock the scenario where the third party sends a redirect and it is followed.

Apologies in advance if this is already possible.

Thank you 🙏

**Comment by richardszalay** [comment]
Hi @f3z0, let me look into this but I feel like this is something that might be handled by the HttpClientHandler. I'm reluctant to add support for it in MockHttp because its focus is on mocking HttpClient to test the way _your_ application handles the results. If we were to add the redirect support in MockHttpHandler, I'm not sure what value that gives us since it's functionally equivallent of simply remove the redirect setup in your test and have the mock return the actual (ie. post-redirect) response

**Comment by richardszalay** [comment]
I'm going to close this issue as I haven't heard back from you (a bit rich considering my response times!), but I'm more than happy to open it again if need be.
