### ISSUE TITLE
When reading request body MockHttp throws exception

### ISSUE THREAD

**Issue by StummeJ** [richardszalay/mockhttp#28]
An exception is thrown when using an `Expect` with `WithFormData` throws a null object exception when reading the results from `ReadToStringAsync`.  This is with ASP.Net Core 1.1.0 running on the 4.6.1 framework.

**Comment by richardszalay** [comment]
Hi James,

I'm not able to reproduce this. My guess is that your request isn't actually matching your `Expect` so it's returns `404 No matching mock handler` (or whatever you have configured `MockHttpMessageHandler.Fallback` to return). Since this default response doesn't have content, your call to `ReadToReadAsync` is throwing a NRE.

You can confirm this by either inspecting the result for the status/text above, or by simply adding `handler.Fallback.Throw(new InvalidOperationException("No match!"));` which will throw an exception instead.

Failing all of that, can you supply a small snippet of code that reproduces the problem?

**Comment by StummeJ** [comment]
I tried it on another computer and everything is working as expected.  Sorry for the issue.

Cheers!
