### ISSUE TITLE
StatusCode 404

### ISSUE THREAD

**Issue by alexanderparraEway** [richardszalay/mockhttp#32]
I 'm trying to mock my restful adapter , but I have an exception 404 No matching mock handler

this my code

 var httpMockHandler = new MockHttpMessageHandler();
httpMockHandler.When(HttpMethod.Post,"https://api.sandbox.ewaypayments.com/encrypt")
                    .WithContent(data)
                    .Respond("application/json",expectedResponse);
var client = new HttpClient(httpMockHandler);
var response = await client.GetAsync("https://api.sandbox.ewaypayments.com/encrypt");
httpMockHandler.VerifyNoOutstandingExpectation();
var result = await response.Content.ReadAsStringAsync();

 I dont know what I did wrong,Can you please help me?

**Comment by richardszalay** [comment]
Hi there,

It looks like your mocking a response for a POST request with a specific request body, but then actually sending a GET request. The fact that it's taking falling back to the default "no match" response makes sense in this scenario. 

Try changing your mock to match the request.

Also, there's no need to call `VerifyNoOutstandingExpectation` since you're using `When` and not `Expect`.

**Comment by alexanderparraEway** [comment]
I changed for client.PostAsync and it works. I'm newbie in c# 
Thanks alot

**Comment by richardszalay** [comment]
No worries, glad you managed to solve it!
