### ISSUE TITLE
Support for verifying a request was made

### ISSUE THREAD

**Issue by dpix** [richardszalay/mockhttp#35]
Firstly, this is a great library 👍 

It would be great to have a verify method somewhat like that in Moq. So that I can verify that my HttpClient made was called at all with the correct URL, regardless of response. Could also include functionality for expecting a particular response.

e.g.
```c#
new MockHttpMessageHandler().VerifyUrlFetched("some url", Times.Once);
```

Is this something you would consider adding to the API?

**Comment by richardszalay** [comment]
This functionality is somewhat supported using `Expect` instead of `When`, but that's more akin to an ordered mock than a post-verify.

Could you talk through the details of your scenario so I can understand it better?

**Comment by dpix** [comment]
I want to be able to test that the url requested was expected for the scenario, regardless of the response. `Expect` still requires me to check the response.

e.g. (pseudo code)
```c#
void MethodToTest(){
    var url = someMethodThatGeneratesAUrl();
    if(someCondition){
        httpClient.GetAsync(url);
    }

   ......
}
```

Then in my test, all I want to do is check that GetAsync was called exactly one time with the correct url given the condition.

```c#
void TestMethod(){
    MethodToTest();
    mockedClient.VerifyUrl(theUrlExpected, Times.Once); // or Times.Never if I expect it not to get called
}
```

Does that explain it a little better? Happy to help out with a PR, am curious if this is functionality you would consider adding.

**Comment by richardszalay** [comment]
This was just released in 3.2.0

**Comment by richardszalay** [comment]
Hi @dpix,

Just to follow up, the implementation I ended up going for was to track the number of times a specific `IMockedRequest` (returned by `When` / `Expect`) was called.

The reason I went in this direction is that using a URL would have raised questions around matching with/without querystring (or the order of keys), which would lead back to `IMockedRequest` anyway.

The reason it matches against an existing _instance_ of `IMockedRequest`, rather than simply evaluating the matched HttpRequestMessages against the supplied mocked request, is that a number of the matchers require access to the `Content` and that may no longer be available.

Hope that make sense. I've also added an example to the README:

```
var mockHttp = new MockHttpMessageHandler();

var request = mockHttp.When("http://localhost/api/user/*")
        .Respond("application/json", "{'name' : 'Test McGee'}");

var client = mockHttp.ToHttpClient();

await client.GetAsync("http://localhost/api/user/1234");
await client.GetAsync("http://localhost/api/user/2345");
await client.GetAsync("http://localhost/api/user/3456");

Console.Write(mockHttp.GetMatchCount(request)); // 3
```

PS. I do generally promote PRs and discussion around features, but I haven't had a lot of time to work on the library so when I had the chance I ran through all of the feature I thought I could do at one time.

**Comment by dpix** [comment]
Looks great @richardszalay! I'll make sure to update and check it out next I'm updating the tests I was working on

**Comment by stankansas** [comment]
I have this to verify, just wondering how I can do it using MockHttpMessageHandler
```
_httpMessageHandlerMock.Protected().Verify(
    "SendAsync",
    Times.AtLeastOnce(),
    ItExpr.Is<HttpRequestMessage>(req =>
        req.Content.ReadAsStringAsync().Result.Contains(DateTime.UtcNow.AddDays(-7).ToString("yyyy-MM-dd'T'HH:mm:ss.fff'Z'"))),
    ItExpr.IsAny<CancellationToken>());
```

**Comment by richardszalay** [comment]
@stankansas This type of query would be better asked via [Discussions](https://github.com/richardszalay/mockhttp/discussions), but this would be equivalent:

```
var mockHttp = new MockHttpMessageHandler();

var mockedRequest = mockHttp.When("*")
    .WithPartialContent(DateTime.UtcNow.AddDays(-7).ToString("yyyy-MM-dd'T'HH:mm:ss.fff'Z'"))
    .Response(HttpStatusCode.Ok);


Assert.Equals(1, mockHttp.GetMatchCount(mockedRequest));
```

Moq vs MockHttp aside, it's worth calling out that you're not going to get very far with an expectation that's based on the current time down to the millisecond since that will certainly change by the time the request is actually sent.

**Comment by stankansas** [comment]
Thanks Richard, it worked.

didn't know about Discussions, will use it from now on
